#!/usr/bin/env node
/**
 * Canonical workflow event vocabulary, shared by the ledger-integrity
 * validator. Keep in sync with workflow/events.md and the
 * ALLOWED_EVENTS array in scripts/workflow-event (checked by
 * tests/workflow-event-smoke.sh).
 */
export const WORKFLOW_EVENTS = [
	"route_decided",
	"plan_created",
	"adversary_completed",
	"review_completed",
	"simplification_completed",
	"quality_completed",
	"ship_completed",
	"file_changed",
	"validation_run",
	"validation_failed",
	"dogfood_matrix_created",
	"dogfood_scenario_run",
	"dogfood_fix_applied",
	"dogfood_blocked",
	"self_improvement_candidate",
	"harness_failure_pattern",
	"harness_proposal",
	"harness_validation_completed",
	"harness_candidate_rejected",
	"project_slice_planned",
	"project_slice_completed",
	"program_initialized",
	"program_unit_started",
	"program_unit_result",
	"program_unit_verdict",
	"program_unit_head_changed",
	"program_unit_retry",
	"program_unit_reconciled",
	"runtime_run_attached",
	"multi_execution_completed",
	"outcome_measurement_population",
	"outcome_measurement_imported",
	"outcome_metric",
	"runtime_receipt",
	"retry_classified",
	"no_progress",
	"handoff",
	"human_checkpoint",
	"archive_written",
	"plan_removed",
	"completed",
	"blocked",
];
